steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/quickstart-image', '-f','./Dockerfiles/Prod/Dockerfile','.' ]
images:
- 'gcr.io/$PROJECT_ID/quickstart-image'